### ISSUE TITLE
Package contains ES6 syntax

### ISSUE THREAD

**Issue by DaveVdE** [benrlodge/react-simplemde-editor#13]
We're having some trouble using this package because our pipeline currently does not transpile external modules into the ES5 that the browser loves. This is intentional. [Package maintainers should still target ES5](http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/), or am I wrong?

Anyway, we've forked the repo to replace the use of arrow functions until this is solved.

**Comment by benrlodge** [comment]
yea I should have included this from the start - I've added a dist folder that has compiled to es5 files

https://github.com/benrlodge/react-simplemde-editor/pull/14. npm version `3.3.1` includes this.

should be all set, let me know if you run into any issues.
