### ISSUE TITLE
Error fs

### ISSUE THREAD

**Issue by EQuimper** [benrlodge/react-simplemde-editor#19]
I got this in the console when I install your packages and import the module

`Error in ./~/typo-js/typo.js Module not found: Error: Cannot resolve module 'fs'`

**Comment by benrlodge** [comment]
Thanks for bringing this to my attention, working on a fix now.

**Comment by benrlodge** [comment]
I pushed a temporary fix with v3.6.1

This issue has been on my radar when working on tests, but didn't realize it broke the component. https://github.com/cfinke/Typo.js/issues/42

**Comment by EQuimper** [comment]
Perfect thank you

**Comment by benrlodge** [comment]
should be resolved with https://github.com/benrlodge/react-simplemde-editor/pull/32 

v.3.6.6
