### ISSUE TITLE
setting ininital value with passing "value" to the options doesn't work

### ISSUE THREAD

**Issue by omarkhaled11** [benrlodge/react-simplemde-editor#29]
passing "value" as an option doesn't set the initial state during first render, it showed the editor empty, passing it as initialValue though in options just like the Simple mde configuration options worked for me.

just wanted to share it in case somebody had trouble with this.

All in all great package thanks a lot.

**Comment by benrlodge** [comment]
thanks for picking up on this - that was a typo in the docs
