### ISSUE TITLE
Problems with server-side rendering. Navigator is not defined

### ISSUE THREAD

**Issue by RIP21** [benrlodge/react-simplemde-editor#30]
This component is actually cannot work with server-side rendering applications. And throws error looks like
` ReferenceError: navigator is not defined`
It's a problem with codemirror component which is dependency of original simplemde project.
I already have a proven workaround which is used in `react-codemirror` project.
PR request will be in a few minutes.

**Comment by benrlodge** [comment]
should be fixed with https://github.com/benrlodge/react-simplemde-editor/pull/31

**Comment by shubhsk88** [comment]
Does this issue got resolved because I am also getting the same error in `next`? If so can someone provide me the workaround for it?

**Comment by RIP21** [comment]
@shubhsk88 you need to make sure you import SimpleMDE dynamically or with `ssr` flag to false or similar so code of this library runs only on client and never on backend. Search for issues, I think the example was somewhere mentioned.

**Comment by pdichone** [comment]
Hey guys, so I am running into the same issue with SimpleMD in a nextjs app trying to push it to the AWS server.  Any solutions that work as of today?  
Thank you so much. Any help/assistance is greatly appreciated.
@shubhsk88  @RIP21

**Comment by RIP21** [comment]
@pdichone 
```ts
const SimpleMDE = dynamic(() => import('react-simplemde-editor'), { ssr: false })
```

Then render as usual wherever you want.

**Comment by pdichone** [comment]
@RIP21  Thnak you a bunch!! It works! Thank you!

**Comment by fkotsian** [comment]
Hey y'all, thanks for this awesome lib! Just wanted to say that if you're using a non-Nextjs SSR like me (react-rails), can confirm a standard React.lazy + Suspense dynamic import works. Hope it saves you some time: https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by Dev-Dz27** [comment]
for those who are having this issue with Next.js 13 you may just forgot to use the 'use client' at the top of your component, that solved it for me and Next.js didn't suggested it just said : ( node_modules\codemirror\lib\codemirror.js (18:0) @ eval
 ⨯ ReferenceError: navigator is not defined
    at __webpack_require__ (D:\Vs Code\Next js\Next 13\issue-tracker\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (D:\Vs Code\Next js\Next 13\issue-tracker\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (D:\Vs Code\Next js\Next 13\issue-tracker\.next\server\webpack-runtime.js:33:43)
    at eval (./app/issues/new/page.tsx:9:80)
    at (ssr)/./app/issues/new/page.tsx (D:\Vs Code\Next js\Next 13\issue-tracker\.next\server\app\issues\new\page.js:173:1)        
    at __webpack_require__ (D:\Vs Code\Next js\Next 13\issue-tracker\.next\server\webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
null)

**Comment by mhraihan** [comment]
> for those who are having this issue with Next.js 13 you may just forgot to use the 'use client' at the top of your component, that solved it for me and Next.js didn't suggested it just said : ( node_modules\codemirror\lib\codemirror.js (18:0) @ eval ⨯ ReferenceError: navigator is not defined at **webpack_require** (D:\Vs Code\Next js\Next 13\issue-tracker.next\server\webpack-runtime.js:33:43) at **webpack_require** (D:\Vs Code\Next js\Next 13\issue-tracker.next\server\webpack-runtime.js:33:43) at **webpack_require** (D:\Vs Code\Next js\Next 13\issue-tracker.next\server\webpack-runtime.js:33:43) at eval (./app/issues/new/page.tsx:9:80) at (ssr)/./app/issues/new/page.tsx (D:\Vs Code\Next js\Next 13\issue-tracker.next\server\app\issues\new\page.js:173:1) at **webpack_require** (D:\Vs Code\Next js\Next 13\issue-tracker.next\server\webpack-runtime.js:33:43) at JSON.parse () null)

```"use client";```
@Dev-Dz27  unfortunately, does not solved the issue for me. :( 

but @RIP21 suggested worked

thanks
