### ISSUE TITLE
Latest version 3.6.6 don't have changes included in source files bundled in dist

### ISSUE THREAD

**Issue by RIP21** [benrlodge/react-simplemde-editor#33]
Imports by default is importing `react-simplemde-editor.js` which is in the dist folder. And that one don't have changes that have been added into the source code in version 3.6.5. (solving navigator and id problems for server-side rendering)

Please rebuild and deploy it again making sure that changes are appear in `react-simplemde-editor.js` file in dist folder.
Maybe it was my mistake, that I didn't commit dist with new changes to not spam into diffs. But you didn't notice that in pull request and released it as is :) 
Sorry :)
And please add to the readme.md info that you can set static id for this component to avoid errors in server-side rendering synchronization so people now that this is available and do not open an issue for that.

Thanks.

Workaround for this issue is just explicitly import `react-simplemde-editor/src/index.js`

**Comment by benrlodge** [comment]
my bad, need to make make that automated. should be all set.
