### ISSUE TITLE
How can I get and set the cursor position?

### ISSUE THREAD

**Issue by raymestalez** [benrlodge/react-simplemde-editor#46]
It would be really awesome if I could get and then set the cursor position, or at least change the default behavior so that the cursor would be at the end of the text, not the begninning.

Can you help me out?

**Comment by jrsinclair** [comment]
See !45. I think a few of us are having the same issue.

**Comment by jrsinclair** [comment]
Sorry, that should be pull request #45

**Comment by ftxrc** [comment]
It'd be great to see that pull request merged. I ran into the same exact issue and I'm having a hard time with it.

**Comment by benrlodge** [comment]
all set https://github.com/benrlodge/react-simplemde-editor/commit/1f12234b971fa7b57f2cf87467ee4c1baeb59394

**Comment by towc** [comment]
I have a similar issue. I'm changing the content myself because I set every instance of a certain character (say, `<`), with another [set] ( say, `\<`). But when I do that, cursor goes on top. Sounds fair, but not sure what to do with it
