### ISSUE TITLE
Any way to control value directly

### ISSUE THREAD

**Issue by eoinmurray** [benrlodge/react-simplemde-editor#5]
Instead of using `initialValue`...

Something like:

```
<ReactSimpleMDE
    value: this.props.value
/>
```

So that it can be controlled by some higher level component?

**Comment by benrlodge** [comment]
Can you explain the use case in more detail? 

Does setting the initial value using props not get what you wish to achieve? -

```javascript
<ReactSimpleMDE
    initialValue: this.props.value
/>
```

**Comment by eoinmurray** [comment]
it only sets the initial value - so if somewhere higher up the component hierarchy the value changes then currently ReactSimpleMDE doesn't reflect that

**Comment by benrlodge** [comment]
Sure, I see what your saying, thanks for pointing out. My simple use case never exposed this issue. I'll be pushing an update shortly.
